version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - npm clean-install-test      
  build:
    commands:
      - npm publish $PUBLISH_ARGS --unsafe-perm